-- ======================================================================
-- INSERT delete postbox template
-- ======================================================================
INSERT INTO `emails` (`slug`, `subject`, `description`, `content`) VALUES
	('delete_postbox_account', 'clevverMail - Downgraded business account', 'Send email notification when one customer deleted postbox.', '<br />\r\nDear team,<br />\r\n<p>\r\n	&nbsp;</p>\r\n<p>\r\n	This business account has been <span style="color: rgb(51, 51, 51); font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;"><span style="color: rgb(51, 51, 51); font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;">deleted</span></span> when you deleted your postbox.</p>\r\n<p>\r\n	Email address: {{email}}</p>\r\n<p>\r\n	Postbox Name: {{postbox_name}}</p>\r\n<p>\r\n	Name: {{name}}</p>\r\n<p>\r\n	Company: {{company}}</p>\r\n<p>\r\n	&nbsp;</p>\r\n<p>\r\n	Best regards,</p>\r\n<p>\r\n	ClevverMail</p>');


-- ======================================================================
-- INSERT delete postbox template
-- ======================================================================
UPDATE `emails` SET `content`='Dear team,<br />\r\n<p>\r\n	&nbsp;</p>\r\n<p>\r\n	This business account has been <span style="color: rgb(51, 51, 51); font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;"><span style="color: rgb(51, 51, 51); font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none;">downgraded/canceled</span></span></p>\r\n<p>\r\n	Email address: {{email}}</p>\r\n<p>\r\n	Postbox Name: {{postbox_name}}</p>\r\n<p>\r\n	Name: {{name}}</p>\r\n<p>\r\n	Company: {{company}}</p>\r\n<p>\r\n	&nbsp;</p>\r\n<p>\r\n	Best regards,</p>\r\n<p>\r\n	ClevverMail</p>'
WHERE `slug`='downgraded_business_account'


