CREATE TABLE `user_paging` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) DEFAULT NULL,
  `setting_key` VARCHAR(20) DEFAULT NULL,
  `setting_value` VARCHAR(20) DEFAULT NULL,
  `user_type` INTEGER(11) DEFAULT '0',
  primary key(id)
)ENGINE=InnoDB COMMENT='' CHECKSUM=0 DELAY_KEY_WRITE=0 PACK_KEYS=0 MIN_ROWS=0 MAX_ROWS=0 ROW_FORMAT=COMPACT CHARACTER SET 'utf8'
COLLATE 'utf8_general_ci';

COMMIT;
