/*
Navicat MySQL Data Transfer
Source Host     : localhost:3306
Source Database : clevvermail01
Target Host     : localhost:3306
Target Database : clevvermail01
Date: 2015-04-28 23:57:41
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for pricing
-- ----------------------------
DROP TABLE IF EXISTS `pricing`;
CREATE TABLE `pricing` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `account_type` tinyint(4) DEFAULT NULL COMMENT 'Reference: 000033',
  `item_name` varchar(250) DEFAULT NULL,
  `item_value` varchar(250) DEFAULT NULL,
  `item_description` varchar(255) DEFAULT NULL,
  `item_unit` varchar(255) DEFAULT NULL,
  `pricing_template_id` int(11) NOT NULL DEFAULT '0',
  `type` int(11) DEFAULT NULL COMMENT '0:local service| 1:digital good | 2: shipping.',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=908 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of pricing
-- ----------------------------
INSERT INTO `pricing` VALUES ('76', '1', 'address_number', '1', 'address', 'numbers', '1', '1');
INSERT INTO `pricing` VALUES ('77', '1', 'included_incomming_items', '0', 'included incomming items', null, '1', '1');
INSERT INTO `pricing` VALUES ('78', '1', 'storage', '1', 'storage', 'GB', '1', '1');
INSERT INTO `pricing` VALUES ('79', '1', 'hand_sorting_of_advertising', 'No', 'hand sorting of advertising', null, '1', '1');
INSERT INTO `pricing` VALUES ('80', '1', 'envelope_scanning_front', '5', 'envelope scanning (front)', null, '1', '1');
INSERT INTO `pricing` VALUES ('81', '1', 'included_opening_scanning', '0', 'included opening and scanning', null, '1', '1');
INSERT INTO `pricing` VALUES ('82', '1', 'storing_items_letters', '4', 'storing items (letters)', 'weeks', '1', '1');
INSERT INTO `pricing` VALUES ('83', '1', 'storing_items_packages', '1', 'storing items (packages)', 'week', '1', '1');
INSERT INTO `pricing` VALUES ('84', '1', 'storing_items_digitally', '1', 'storing items digitally', 'year', '1', '1');
INSERT INTO `pricing` VALUES ('85', '1', 'trashing_items', '-1', 'trashing items', 'unlimited', '1', '1');
INSERT INTO `pricing` VALUES ('86', '1', 'cloud_service_connection', 'Yes', 'cloud service connection', 'included', '1', '1');
INSERT INTO `pricing` VALUES ('87', '1', 'additional_incomming_items', '0.42', 'additional incomming items', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('88', '1', 'envelop_scanning', '0.17', 'envelop scanning', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('89', '1', 'opening_scanning', '0.84', 'opening and scanning', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('90', '1', 'send_out_directly', '0.84', 'send out to original address directly', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('91', '1', 'send_out_collected', '1.68', 'send out to original address collected', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('92', '1', 'storing_items_over_free_letter', '0.04', 'storing items over free period (letters)', 'EUR/day', '1', '1');
INSERT INTO `pricing` VALUES ('93', '1', 'storing_items_over_free_packages', '0.17', 'storing items over free period (packages)', 'EUR/day', '1', '1');
INSERT INTO `pricing` VALUES ('94', '1', 'additional_private_mailbox', '4.16', 'additional private mailbox', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('95', '1', 'additional_business_mailbox', '8.36', 'additional business mailbox ', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('96', '2', 'address_number', '1', 'address', 'numbers', '1', '1');
INSERT INTO `pricing` VALUES ('97', '2', 'included_incomming_items', '10', 'included incomming items', null, '1', '1');
INSERT INTO `pricing` VALUES ('98', '2', 'storage', '0', 'storage', 'GB', '1', '1');
INSERT INTO `pricing` VALUES ('99', '2', 'hand_sorting_of_advertising', 'Yes', 'hand sorting of advertising', null, '1', '1');
INSERT INTO `pricing` VALUES ('100', '2', 'envelope_scanning_front', '10', 'envelope scanning (front)', null, '1', '1');
INSERT INTO `pricing` VALUES ('101', '2', 'included_opening_scanning', '5', 'included opening and scanning', null, '1', '1');
INSERT INTO `pricing` VALUES ('102', '2', 'storing_items_letters', '4', 'storing items (letters)', 'weeks', '1', '1');
INSERT INTO `pricing` VALUES ('103', '2', 'storing_items_packages', '1', 'storing items (packages)', 'week', '1', '1');
INSERT INTO `pricing` VALUES ('104', '2', 'storing_items_digitally', '1', 'storing items digitally', 'year', '1', '1');
INSERT INTO `pricing` VALUES ('105', '2', 'trashing_items', '-1', 'trashing items', 'unlimited', '1', '1');
INSERT INTO `pricing` VALUES ('106', '2', 'cloud_service_connection', 'Yes', 'cloud service connection', 'included', '1', '1');
INSERT INTO `pricing` VALUES ('107', '2', 'additional_incomming_items', '0.3', 'additional incomming items', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('108', '2', 'envelop_scanning', '0.1', 'envelop scanning', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('109', '2', 'opening_scanning', '0.5', 'opening and scanning', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('110', '2', 'send_out_directly', '0.5', 'send out to original address directly', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('111', '2', 'send_out_collected', '1', 'send out to original address collected', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('112', '2', 'storing_items_over_free_letter', '0.04', 'storing items over free period (letters)', 'EUR/day', '1', '1');
INSERT INTO `pricing` VALUES ('113', '2', 'storing_items_over_free_packages', '0.15', 'storing items over free period (packages)', 'EUR/day', '1', '1');
INSERT INTO `pricing` VALUES ('114', '2', 'additional_private_mailbox', '4.16', 'additional private mailbox', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('115', '2', 'additional_business_mailbox', '8.36', 'additional business mailbox ', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('116', '3', 'address_number', '1', 'address', 'numbers', '1', '1');
INSERT INTO `pricing` VALUES ('117', '3', 'included_incomming_items', '50', 'included incomming items', null, '1', '1');
INSERT INTO `pricing` VALUES ('118', '3', 'storage', '0', 'storage', 'GB', '1', '1');
INSERT INTO `pricing` VALUES ('119', '3', 'hand_sorting_of_advertising', 'Yes', 'hand sorting of advertising', null, '1', '1');
INSERT INTO `pricing` VALUES ('120', '3', 'envelope_scanning_front', '50', 'envelope scanning (front)', null, '1', '1');
INSERT INTO `pricing` VALUES ('121', '3', 'included_opening_scanning', '10', 'included opening and scanning', null, '1', '1');
INSERT INTO `pricing` VALUES ('122', '3', 'storing_items_letters', '4', 'storing items (letters)', 'weeks', '1', '1');
INSERT INTO `pricing` VALUES ('123', '3', 'storing_items_packages', '1', 'storing items (packages)', 'week', '1', '1');
INSERT INTO `pricing` VALUES ('124', '3', 'storing_items_digitally', '1', 'storing items digitally', 'year', '1', '1');
INSERT INTO `pricing` VALUES ('125', '3', 'trashing_items', '-1', 'trashing items', 'unlimited', '1', '1');
INSERT INTO `pricing` VALUES ('126', '3', 'cloud_service_connection', 'Yes', 'cloud service connection', 'included', '1', '1');
INSERT INTO `pricing` VALUES ('127', '3', 'additional_incomming_items', '0.17', 'additional incomming items', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('128', '3', 'envelop_scanning', '0.042', 'envelop scanning', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('129', '3', 'opening_scanning', '0.34', 'opening and scanning', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('130', '3', 'send_out_directly', '0.34', 'send out to original address directly', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('131', '3', 'send_out_collected', '0.67', 'send out to original address collected', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('132', '3', 'storing_items_over_free_letter', '0.03', 'storing items over free period (letters)', 'EUR/day', '1', '1');
INSERT INTO `pricing` VALUES ('133', '3', 'storing_items_over_free_packages', '0.08', 'storing items over free period (packages)', 'EUR/day', '1', '1');
INSERT INTO `pricing` VALUES ('134', '3', 'additional_private_mailbox', '4.16', 'additional private mailbox', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('135', '3', 'additional_business_mailbox', '8.36', 'additional business mailbox ', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('136', '1', 'postbox_fee', '0', 'fee for first postbox', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('137', '2', 'postbox_fee', '4.16', 'postbox fee for first', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('138', '3', 'postbox_fee', '8.36', 'Postbox fee for first', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('139', '1', 'additional_pages_scanning_price', '0.07', 'Additional pages scanning / 1 page', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('140', '2', 'additional_pages_scanning_price', '0.07', 'Additional pages scanning / 1 page', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('141', '3', 'additional_pages_scanning_price', '0.07', 'Additional pages scanning / 1 page', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('142', '1', 'include_pages_scanning_number', '10', 'Include pages scanning number', 'numbers', '1', null);
INSERT INTO `pricing` VALUES ('143', '2', 'include_pages_scanning_number', '10', 'Include pages scanning number', 'numbers', '1', null);
INSERT INTO `pricing` VALUES ('144', '3', 'include_pages_scanning_number', '10', 'Include pages scanning number', 'numbers', '1', null);
INSERT INTO `pricing` VALUES ('145', '1', 'shipping_plus', '20', 'shipping plus', '%', '1', '1');
INSERT INTO `pricing` VALUES ('146', '2', 'shipping_plus', '20', 'shipping plus', '%', '1', '1');
INSERT INTO `pricing` VALUES ('147', '3', 'shipping_plus', '20', 'shipping plus', '%', '1', '1');
INSERT INTO `pricing` VALUES ('148', '1', 'price_for_additional', '20', 'price for additional pages', 'c', '1', null);
INSERT INTO `pricing` VALUES ('149', '2', 'price_for_additional', '15', 'price for additional pages', 'c', '1', null);
INSERT INTO `pricing` VALUES ('150', '3', 'price_for_additional', '10', 'price for additional pages', 'c', '1', null);
INSERT INTO `pricing` VALUES ('346', '1', 'additional_included_page_opening_scanning', '10', 'Additional Included pages for opening and scanning', 'page', '1', '1');
INSERT INTO `pricing` VALUES ('347', '2', 'additional_included_page_opening_scanning', '10', 'Additional Included pages for opening and scanning', 'page', '1', '1');
INSERT INTO `pricing` VALUES ('348', '3', 'additional_included_page_opening_scanning', '10', 'Additional Included pages for opening and scanning', 'page', '1', '1');
INSERT INTO `pricing` VALUES ('349', '1', 'additional_price_included_page_opening_scanning', '0.2', 'Additional Included pages for opening and scanning', '%', '1', '1');
INSERT INTO `pricing` VALUES ('350', '2', 'additional_price_included_page_opening_scanning', '0.2', 'Additional Included pages for opening and scanning', '%', '1', '1');
INSERT INTO `pricing` VALUES ('351', '3', 'additional_price_included_page_opening_scanning', '0.2', 'Additional Included pages for opening and scanning', '%', '1', '1');
INSERT INTO `pricing` VALUES ('355', '1', 'custom_handling_import', '20', 'customs handling import ', '%', '1', '1');
INSERT INTO `pricing` VALUES ('356', '2', 'custom_handling_import', '20', 'customs handling import ', '%', '1', '1');
INSERT INTO `pricing` VALUES ('357', '3', 'custom_handling_import', '20', 'customs handling import ', '%', '1', '1');
INSERT INTO `pricing` VALUES ('358', '1', 'cash_payment_on_delivery_percentage', '10', 'Cash payment for item on delivery (percentage)', '%', '1', '1');
INSERT INTO `pricing` VALUES ('359', '2', 'cash_payment_on_delivery_percentage', '10', 'Cash payment for item on delivery (percentage)', '%', '1', '1');
INSERT INTO `pricing` VALUES ('360', '3', 'cash_payment_on_delivery_percentage', '10', 'Cash payment for item on delivery (percentage)', '%', '1', '1');
INSERT INTO `pricing` VALUES ('361', '1', 'cash_payment_on_delivery_mini_cost', '5', 'Cash payment for item on delivery (minimum cost)', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('362', '2', 'cash_payment_on_delivery_mini_cost', '5', 'Cash payment for item on delivery (minimum cost)', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('363', '3', 'cash_payment_on_delivery_mini_cost', '5', 'Cash payment for item on delivery (minimum cost)', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('364', '1', 'official_address_verification', '10', 'official address verification', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('365', '2', 'official_address_verification', '10', 'official address verification', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('366', '3', 'official_address_verification', '10', 'official address verification', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('382', '1', 'custom_declaration_outgoing_01', '59', 'Customs declaration outgoing (value >1000 EUR)', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('383', '2', 'custom_declaration_outgoing_01', '59', 'Customs declaration outgoing (value >1000 EUR)', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('384', '3', 'custom_declaration_outgoing_01', '59', 'Customs declaration outgoing (value >1000 EUR)', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('385', '1', 'custom_declaration_outgoing_02', '10', 'Customs declaration outgoing (value <1000 EUR)', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('386', '2', 'custom_declaration_outgoing_02', '10', 'Customs declaration outgoing (value <1000 EUR)', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('387', '3', 'custom_declaration_outgoing_02', '10', 'Customs declaration outgoing (value <1000 EUR)', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('388', '1', 'collect_shipping_plus', '20', 'Shipping collected to forwarding address (percentage on top of postal charge)', '%', '1', '1');
INSERT INTO `pricing` VALUES ('389', '2', 'collect_shipping_plus', '20', 'Shipping collected to forwarding address (percentage on top of postal charge)', '%', '1', '1');
INSERT INTO `pricing` VALUES ('390', '3', 'collect_shipping_plus', '20', 'Shipping collected to forwarding address (percentage on top of postal charge)', '%', '1', '1');
INSERT INTO `pricing` VALUES ('391', '1', 'pickup_charge', '50', 'Pickup charge (only with confirmed appointment)', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('392', '2', 'pickup_charge', '50', 'Pickup charge (only with confirmed appointment)', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('393', '3', 'pickup_charge', '50', 'Pickup charge (only with confirmed appointment)', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('394', '1', 'special_requests_charge_by_time', '60', 'Pickup charge (only with confirmed appointment)', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('395', '2', 'special_requests_charge_by_time', '60', 'Pickup charge (only with confirmed appointment)', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('396', '3', 'special_requests_charge_by_time', '60', 'Pickup charge (only with confirmed appointment)', 'EUR', '1', '1');
INSERT INTO `pricing` VALUES ('651', '1', 'paypal_transaction_fee', '3', 'Pickup charge (only with confirmed appointment)', '%', '1', '1');
INSERT INTO `pricing` VALUES ('652', '2', 'paypal_transaction_fee', '3', 'Pickup charge (only with confirmed appointment)', '%', '1', '1');
INSERT INTO `pricing` VALUES ('653', '3', 'paypal_transaction_fee', '3', 'Pickup charge (only with confirmed appointment)', '%', '1', '1');
INSERT INTO `pricing` VALUES ('654', '1', 'address_number', '1', 'address', 'numbers', '0', '1');
INSERT INTO `pricing` VALUES ('655', '1', 'included_incomming_items', '0', 'included incomming items', null, '0', '1');
INSERT INTO `pricing` VALUES ('656', '1', 'storage', '1', 'storage', 'GB', '0', '1');
INSERT INTO `pricing` VALUES ('657', '1', 'hand_sorting_of_advertising', 'No', 'hand sorting of advertising', null, '0', '1');
INSERT INTO `pricing` VALUES ('658', '1', 'envelope_scanning_front', '5', 'envelope scanning (front)', null, '0', '1');
INSERT INTO `pricing` VALUES ('659', '1', 'included_opening_scanning', '0', 'included opening and scanning', null, '0', '1');
INSERT INTO `pricing` VALUES ('660', '1', 'storing_items_letters', '4', 'storing items (letters)', 'weeks', '0', '1');
INSERT INTO `pricing` VALUES ('661', '1', 'storing_items_packages', '1', 'storing items (packages)', 'week', '0', '1');
INSERT INTO `pricing` VALUES ('662', '1', 'storing_items_digitally', '1', 'storing items digitally', 'year', '0', '1');
INSERT INTO `pricing` VALUES ('663', '1', 'trashing_items', '-1', 'trashing items', 'unlimited', '0', '1');
INSERT INTO `pricing` VALUES ('664', '1', 'cloud_service_connection', 'Yes', 'cloud service connection', 'included', '0', '1');
INSERT INTO `pricing` VALUES ('665', '1', 'additional_incomming_items', '0.42', 'additional incomming items', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('666', '1', 'envelop_scanning', '0.17', 'envelop scanning', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('667', '1', 'opening_scanning', '0.84', 'opening and scanning', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('668', '1', 'send_out_directly', '0.84', 'send out to original address directly', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('669', '1', 'send_out_collected', '1.68', 'send out to original address collected', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('670', '1', 'storing_items_over_free_letter', '0.04', 'storing items over free period (letters)', 'EUR/day', '0', '1');
INSERT INTO `pricing` VALUES ('671', '1', 'storing_items_over_free_packages', '0.17', 'storing items over free period (packages)', 'EUR/day', '0', '1');
INSERT INTO `pricing` VALUES ('672', '1', 'additional_private_mailbox', '4.16', 'additional private mailbox', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('673', '1', 'additional_business_mailbox', '8.36', 'additional business mailbox ', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('674', '2', 'address_number', '1', 'address', 'numbers', '0', '1');
INSERT INTO `pricing` VALUES ('675', '2', 'included_incomming_items', '10', 'included incomming items', null, '0', '1');
INSERT INTO `pricing` VALUES ('676', '2', 'storage', '0', 'storage', 'GB', '0', '1');
INSERT INTO `pricing` VALUES ('677', '2', 'hand_sorting_of_advertising', 'Yes', 'hand sorting of advertising', null, '0', '1');
INSERT INTO `pricing` VALUES ('678', '2', 'envelope_scanning_front', '10', 'envelope scanning (front)', null, '0', '1');
INSERT INTO `pricing` VALUES ('679', '2', 'included_opening_scanning', '5', 'included opening and scanning', null, '0', '1');
INSERT INTO `pricing` VALUES ('680', '2', 'storing_items_letters', '4', 'storing items (letters)', 'weeks', '0', '1');
INSERT INTO `pricing` VALUES ('681', '2', 'storing_items_packages', '1', 'storing items (packages)', 'week', '0', '1');
INSERT INTO `pricing` VALUES ('682', '2', 'storing_items_digitally', '1', 'storing items digitally', 'year', '0', '1');
INSERT INTO `pricing` VALUES ('683', '2', 'trashing_items', '-1', 'trashing items', 'unlimited', '0', '1');
INSERT INTO `pricing` VALUES ('684', '2', 'cloud_service_connection', 'Yes', 'cloud service connection', 'included', '0', '1');
INSERT INTO `pricing` VALUES ('685', '2', 'additional_incomming_items', '0.3', 'additional incomming items', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('686', '2', 'envelop_scanning', '0.1', 'envelop scanning', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('687', '2', 'opening_scanning', '0.5', 'opening and scanning', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('688', '2', 'send_out_directly', '0.5', 'send out to original address directly', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('689', '2', 'send_out_collected', '1', 'send out to original address collected', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('690', '2', 'storing_items_over_free_letter', '0.04', 'storing items over free period (letters)', 'EUR/day', '0', '1');
INSERT INTO `pricing` VALUES ('691', '2', 'storing_items_over_free_packages', '0.15', 'storing items over free period (packages)', 'EUR/day', '0', '1');
INSERT INTO `pricing` VALUES ('692', '2', 'additional_private_mailbox', '4.16', 'additional private mailbox', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('693', '2', 'additional_business_mailbox', '8.36', 'additional business mailbox ', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('694', '3', 'address_number', '1', 'address', 'numbers', '0', '1');
INSERT INTO `pricing` VALUES ('695', '3', 'included_incomming_items', '50', 'included incomming items', null, '0', '1');
INSERT INTO `pricing` VALUES ('696', '3', 'storage', '0', 'storage', 'GB', '0', '1');
INSERT INTO `pricing` VALUES ('697', '3', 'hand_sorting_of_advertising', 'Yes', 'hand sorting of advertising', null, '0', '1');
INSERT INTO `pricing` VALUES ('698', '3', 'envelope_scanning_front', '50', 'envelope scanning (front)', null, '0', '1');
INSERT INTO `pricing` VALUES ('699', '3', 'included_opening_scanning', '10', 'included opening and scanning', null, '0', '1');
INSERT INTO `pricing` VALUES ('700', '3', 'storing_items_letters', '4', 'storing items (letters)', 'weeks', '0', '1');
INSERT INTO `pricing` VALUES ('701', '3', 'storing_items_packages', '1', 'storing items (packages)', 'week', '0', '1');
INSERT INTO `pricing` VALUES ('702', '3', 'storing_items_digitally', '1', 'storing items digitally', 'year', '0', '1');
INSERT INTO `pricing` VALUES ('703', '3', 'trashing_items', '-1', 'trashing items', 'unlimited', '0', '1');
INSERT INTO `pricing` VALUES ('704', '3', 'cloud_service_connection', 'Yes', 'cloud service connection', 'included', '0', '1');
INSERT INTO `pricing` VALUES ('705', '3', 'additional_incomming_items', '0.17', 'additional incomming items', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('706', '3', 'envelop_scanning', '0.042', 'envelop scanning', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('707', '3', 'opening_scanning', '0.34', 'opening and scanning', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('708', '3', 'send_out_directly', '0.34', 'send out to original address directly', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('709', '3', 'send_out_collected', '0.67', 'send out to original address collected', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('710', '3', 'storing_items_over_free_letter', '0.03', 'storing items over free period (letters)', 'EUR/day', '0', '1');
INSERT INTO `pricing` VALUES ('711', '3', 'storing_items_over_free_packages', '0.08', 'storing items over free period (packages)', 'EUR/day', '0', '1');
INSERT INTO `pricing` VALUES ('712', '3', 'additional_private_mailbox', '4.16', 'additional private mailbox', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('713', '3', 'additional_business_mailbox', '8.36', 'additional business mailbox ', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('714', '1', 'postbox_fee', '0', 'fee for first postbox', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('715', '2', 'postbox_fee', '4.16', 'postbox fee for first', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('716', '3', 'postbox_fee', '8.36', 'Postbox fee for first', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('717', '1', 'additional_pages_scanning_price', '0.07', 'Additional pages scanning / 1 page', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('718', '2', 'additional_pages_scanning_price', '0.07', 'Additional pages scanning / 1 page', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('719', '3', 'additional_pages_scanning_price', '0.07', 'Additional pages scanning / 1 page', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('720', '1', 'include_pages_scanning_number', '10', 'Include pages scanning number', 'numbers', '0', null);
INSERT INTO `pricing` VALUES ('721', '2', 'include_pages_scanning_number', '10', 'Include pages scanning number', 'numbers', '0', null);
INSERT INTO `pricing` VALUES ('722', '3', 'include_pages_scanning_number', '10', 'Include pages scanning number', 'numbers', '0', null);
INSERT INTO `pricing` VALUES ('723', '1', 'shipping_plus', '20', 'shipping plus', '%', '0', '1');
INSERT INTO `pricing` VALUES ('724', '2', 'shipping_plus', '20', 'shipping plus', '%', '0', '1');
INSERT INTO `pricing` VALUES ('725', '3', 'shipping_plus', '20', 'shipping plus', '%', '0', '1');
INSERT INTO `pricing` VALUES ('726', '1', 'price_for_additional', '20', 'price for additional pages', 'c', '0', null);
INSERT INTO `pricing` VALUES ('727', '2', 'price_for_additional', '15', 'price for additional pages', 'c', '0', null);
INSERT INTO `pricing` VALUES ('728', '3', 'price_for_additional', '10', 'price for additional pages', 'c', '0', null);
INSERT INTO `pricing` VALUES ('729', '1', 'additional_included_page_opening_scanning', '10', 'Additional Included pages for opening and scanning', 'page', '0', '1');
INSERT INTO `pricing` VALUES ('730', '2', 'additional_included_page_opening_scanning', '10', 'Additional Included pages for opening and scanning', 'page', '0', '1');
INSERT INTO `pricing` VALUES ('731', '3', 'additional_included_page_opening_scanning', '10', 'Additional Included pages for opening and scanning', 'page', '0', '1');
INSERT INTO `pricing` VALUES ('732', '1', 'additional_price_included_page_opening_scanning', '0.2', 'Additional Included pages for opening and scanning', '%', '0', '1');
INSERT INTO `pricing` VALUES ('733', '2', 'additional_price_included_page_opening_scanning', '0.2', 'Additional Included pages for opening and scanning', '%', '0', '1');
INSERT INTO `pricing` VALUES ('734', '3', 'additional_price_included_page_opening_scanning', '0.2', 'Additional Included pages for opening and scanning', '%', '0', '1');
INSERT INTO `pricing` VALUES ('735', '1', 'custom_handling_import', '20', 'customs handling import ', '%', '0', '1');
INSERT INTO `pricing` VALUES ('736', '2', 'custom_handling_import', '20', 'customs handling import ', '%', '0', '1');
INSERT INTO `pricing` VALUES ('737', '3', 'custom_handling_import', '20', 'customs handling import ', '%', '0', '1');
INSERT INTO `pricing` VALUES ('738', '1', 'cash_payment_on_delivery_percentage', '10', 'Cash payment for item on delivery (percentage)', '%', '0', '1');
INSERT INTO `pricing` VALUES ('739', '2', 'cash_payment_on_delivery_percentage', '10', 'Cash payment for item on delivery (percentage)', '%', '0', '1');
INSERT INTO `pricing` VALUES ('740', '3', 'cash_payment_on_delivery_percentage', '10', 'Cash payment for item on delivery (percentage)', '%', '0', '1');
INSERT INTO `pricing` VALUES ('741', '1', 'cash_payment_on_delivery_mini_cost', '5', 'Cash payment for item on delivery (minimum cost)', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('742', '2', 'cash_payment_on_delivery_mini_cost', '5', 'Cash payment for item on delivery (minimum cost)', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('743', '3', 'cash_payment_on_delivery_mini_cost', '5', 'Cash payment for item on delivery (minimum cost)', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('744', '1', 'official_address_verification', '10', 'official address verification', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('745', '2', 'official_address_verification', '10', 'official address verification', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('746', '3', 'official_address_verification', '10', 'official address verification', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('747', '1', 'custom_declaration_outgoing_01', '59', 'Customs declaration outgoing (value >1000 EUR)', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('748', '2', 'custom_declaration_outgoing_01', '59', 'Customs declaration outgoing (value >1000 EUR)', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('749', '3', 'custom_declaration_outgoing_01', '59', 'Customs declaration outgoing (value >1000 EUR)', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('750', '1', 'custom_declaration_outgoing_02', '10', 'Customs declaration outgoing (value <1000 EUR)', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('751', '2', 'custom_declaration_outgoing_02', '10', 'Customs declaration outgoing (value <1000 EUR)', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('752', '3', 'custom_declaration_outgoing_02', '10', 'Customs declaration outgoing (value <1000 EUR)', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('753', '1', 'collect_shipping_plus', '20', 'Shipping collected to forwarding address (percentage on top of postal charge)', '%', '0', '1');
INSERT INTO `pricing` VALUES ('754', '2', 'collect_shipping_plus', '20', 'Shipping collected to forwarding address (percentage on top of postal charge)', '%', '0', '1');
INSERT INTO `pricing` VALUES ('755', '3', 'collect_shipping_plus', '20', 'Shipping collected to forwarding address (percentage on top of postal charge)', '%', '0', '1');
INSERT INTO `pricing` VALUES ('756', '1', 'pickup_charge', '50', 'Pickup charge (only with confirmed appointment)', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('757', '2', 'pickup_charge', '50', 'Pickup charge (only with confirmed appointment)', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('758', '3', 'pickup_charge', '50', 'Pickup charge (only with confirmed appointment)', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('759', '1', 'special_requests_charge_by_time', '60', 'Pickup charge (only with confirmed appointment)', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('760', '2', 'special_requests_charge_by_time', '60', 'Pickup charge (only with confirmed appointment)', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('761', '3', 'special_requests_charge_by_time', '60', 'Pickup charge (only with confirmed appointment)', 'EUR', '0', '1');
INSERT INTO `pricing` VALUES ('762', '1', 'paypal_transaction_fee', '3', 'Pickup charge (only with confirmed appointment)', '%', '0', '1');
INSERT INTO `pricing` VALUES ('763', '2', 'paypal_transaction_fee', '3', 'Pickup charge (only with confirmed appointment)', '%', '0', '1');
INSERT INTO `pricing` VALUES ('764', '3', 'paypal_transaction_fee', '3', 'Pickup charge (only with confirmed appointment)', '%', '0', '1');
INSERT INTO `pricing` VALUES ('781', '1', 'address_number', '1', 'address', 'numbers', '3', '1');
INSERT INTO `pricing` VALUES ('782', '1', 'included_incomming_items', '0', 'included incomming items', null, '3', '1');
INSERT INTO `pricing` VALUES ('783', '1', 'storage', '1', 'storage', 'GB', '3', '1');
INSERT INTO `pricing` VALUES ('784', '1', 'hand_sorting_of_advertising', 'No', 'hand sorting of advertising', null, '3', '1');
INSERT INTO `pricing` VALUES ('785', '1', 'envelope_scanning_front', '5', 'envelope scanning (front)', null, '3', '1');
INSERT INTO `pricing` VALUES ('786', '1', 'included_opening_scanning', '0', 'included opening and scanning', null, '3', '1');
INSERT INTO `pricing` VALUES ('787', '1', 'storing_items_letters', '4', 'storing items (letters)', 'weeks', '3', '1');
INSERT INTO `pricing` VALUES ('788', '1', 'storing_items_packages', '1', 'storing items (packages)', 'week', '3', '1');
INSERT INTO `pricing` VALUES ('789', '1', 'storing_items_digitally', '1', 'storing items digitally', 'year', '3', '1');
INSERT INTO `pricing` VALUES ('790', '1', 'trashing_items', '-1', 'trashing items', 'unlimited', '3', '1');
INSERT INTO `pricing` VALUES ('791', '1', 'cloud_service_connection', 'Yes', 'cloud service connection', 'included', '3', '1');
INSERT INTO `pricing` VALUES ('792', '1', 'additional_incomming_items', '0.42', 'additional incomming items', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('793', '1', 'envelop_scanning', '0.17', 'envelop scanning', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('794', '1', 'opening_scanning', '0.84', 'opening and scanning', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('795', '1', 'send_out_directly', '0.84', 'send out to original address directly', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('796', '1', 'send_out_collected', '1.68', 'send out to original address collected', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('797', '1', 'storing_items_over_free_letter', '0.04', 'storing items over free period (letters)', 'EUR/day', '3', '1');
INSERT INTO `pricing` VALUES ('798', '1', 'storing_items_over_free_packages', '0.17', 'storing items over free period (packages)', 'EUR/day', '3', '1');
INSERT INTO `pricing` VALUES ('799', '1', 'additional_private_mailbox', '4.16', 'additional private mailbox', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('800', '1', 'additional_business_mailbox', '8.36', 'additional business mailbox ', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('801', '2', 'address_number', '1', 'address', 'numbers', '3', '1');
INSERT INTO `pricing` VALUES ('802', '2', 'included_incomming_items', '10', 'included incomming items', null, '3', '1');
INSERT INTO `pricing` VALUES ('803', '2', 'storage', '0', 'storage', 'GB', '3', '1');
INSERT INTO `pricing` VALUES ('804', '2', 'hand_sorting_of_advertising', 'Yes', 'hand sorting of advertising', null, '3', '1');
INSERT INTO `pricing` VALUES ('805', '2', 'envelope_scanning_front', '10', 'envelope scanning (front)', null, '3', '1');
INSERT INTO `pricing` VALUES ('806', '2', 'included_opening_scanning', '5', 'included opening and scanning', null, '3', '1');
INSERT INTO `pricing` VALUES ('807', '2', 'storing_items_letters', '4', 'storing items (letters)', 'weeks', '3', '1');
INSERT INTO `pricing` VALUES ('808', '2', 'storing_items_packages', '1', 'storing items (packages)', 'week', '3', '1');
INSERT INTO `pricing` VALUES ('809', '2', 'storing_items_digitally', '1', 'storing items digitally', 'year', '3', '1');
INSERT INTO `pricing` VALUES ('810', '2', 'trashing_items', '-1', 'trashing items', 'unlimited', '3', '1');
INSERT INTO `pricing` VALUES ('811', '2', 'cloud_service_connection', 'Yes', 'cloud service connection', 'included', '3', '1');
INSERT INTO `pricing` VALUES ('812', '2', 'additional_incomming_items', '0.3', 'additional incomming items', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('813', '2', 'envelop_scanning', '0.1', 'envelop scanning', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('814', '2', 'opening_scanning', '0.5', 'opening and scanning', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('815', '2', 'send_out_directly', '0.5', 'send out to original address directly', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('816', '2', 'send_out_collected', '1', 'send out to original address collected', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('817', '2', 'storing_items_over_free_letter', '0.04', 'storing items over free period (letters)', 'EUR/day', '3', '1');
INSERT INTO `pricing` VALUES ('818', '2', 'storing_items_over_free_packages', '0.15', 'storing items over free period (packages)', 'EUR/day', '3', '1');
INSERT INTO `pricing` VALUES ('819', '2', 'additional_private_mailbox', '4.16', 'additional private mailbox', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('820', '2', 'additional_business_mailbox', '8.36', 'additional business mailbox ', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('821', '3', 'address_number', '1', 'address', 'numbers', '3', '1');
INSERT INTO `pricing` VALUES ('822', '3', 'included_incomming_items', '50', 'included incomming items', null, '3', '1');
INSERT INTO `pricing` VALUES ('823', '3', 'storage', '0', 'storage', 'GB', '3', '1');
INSERT INTO `pricing` VALUES ('824', '3', 'hand_sorting_of_advertising', 'Yes', 'hand sorting of advertising', null, '3', '1');
INSERT INTO `pricing` VALUES ('825', '3', 'envelope_scanning_front', '50', 'envelope scanning (front)', null, '3', '1');
INSERT INTO `pricing` VALUES ('826', '3', 'included_opening_scanning', '10', 'included opening and scanning', null, '3', '1');
INSERT INTO `pricing` VALUES ('827', '3', 'storing_items_letters', '4', 'storing items (letters)', 'weeks', '3', '1');
INSERT INTO `pricing` VALUES ('828', '3', 'storing_items_packages', '1', 'storing items (packages)', 'week', '3', '1');
INSERT INTO `pricing` VALUES ('829', '3', 'storing_items_digitally', '1', 'storing items digitally', 'year', '3', '1');
INSERT INTO `pricing` VALUES ('830', '3', 'trashing_items', '-1', 'trashing items', 'unlimited', '3', '1');
INSERT INTO `pricing` VALUES ('831', '3', 'cloud_service_connection', 'Yes', 'cloud service connection', 'included', '3', '1');
INSERT INTO `pricing` VALUES ('832', '3', 'additional_incomming_items', '0.17', 'additional incomming items', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('833', '3', 'envelop_scanning', '0.042', 'envelop scanning', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('834', '3', 'opening_scanning', '0.34', 'opening and scanning', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('835', '3', 'send_out_directly', '0.34', 'send out to original address directly', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('836', '3', 'send_out_collected', '0.67', 'send out to original address collected', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('837', '3', 'storing_items_over_free_letter', '0.03', 'storing items over free period (letters)', 'EUR/day', '3', '1');
INSERT INTO `pricing` VALUES ('838', '3', 'storing_items_over_free_packages', '0.08', 'storing items over free period (packages)', 'EUR/day', '3', '1');
INSERT INTO `pricing` VALUES ('839', '3', 'additional_private_mailbox', '4.16', 'additional private mailbox', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('840', '3', 'additional_business_mailbox', '8.36', 'additional business mailbox ', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('841', '1', 'postbox_fee', '0', 'fee for first postbox', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('842', '2', 'postbox_fee', '4.16', 'postbox fee for first', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('843', '3', 'postbox_fee', '8.36', 'Postbox fee for first', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('844', '1', 'additional_pages_scanning_price', '0.07', 'Additional pages scanning / 1 page', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('845', '2', 'additional_pages_scanning_price', '0.07', 'Additional pages scanning / 1 page', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('846', '3', 'additional_pages_scanning_price', '0.07', 'Additional pages scanning / 1 page', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('847', '1', 'include_pages_scanning_number', '10', 'Include pages scanning number', 'numbers', '3', null);
INSERT INTO `pricing` VALUES ('848', '2', 'include_pages_scanning_number', '10', 'Include pages scanning number', 'numbers', '3', null);
INSERT INTO `pricing` VALUES ('849', '3', 'include_pages_scanning_number', '10', 'Include pages scanning number', 'numbers', '3', null);
INSERT INTO `pricing` VALUES ('850', '1', 'shipping_plus', '20', 'shipping plus', '%', '3', '1');
INSERT INTO `pricing` VALUES ('851', '2', 'shipping_plus', '20', 'shipping plus', '%', '3', '1');
INSERT INTO `pricing` VALUES ('852', '3', 'shipping_plus', '20', 'shipping plus', '%', '3', '1');
INSERT INTO `pricing` VALUES ('853', '1', 'price_for_additional', '20', 'price for additional pages', 'c', '3', null);
INSERT INTO `pricing` VALUES ('854', '2', 'price_for_additional', '15', 'price for additional pages', 'c', '3', null);
INSERT INTO `pricing` VALUES ('855', '3', 'price_for_additional', '10', 'price for additional pages', 'c', '3', null);
INSERT INTO `pricing` VALUES ('856', '1', 'additional_included_page_opening_scanning', '10', 'Additional Included pages for opening and scanning', 'page', '3', '1');
INSERT INTO `pricing` VALUES ('857', '2', 'additional_included_page_opening_scanning', '10', 'Additional Included pages for opening and scanning', 'page', '3', '1');
INSERT INTO `pricing` VALUES ('858', '3', 'additional_included_page_opening_scanning', '10', 'Additional Included pages for opening and scanning', 'page', '3', '1');
INSERT INTO `pricing` VALUES ('859', '1', 'additional_price_included_page_opening_scanning', '0.2', 'Additional Included pages for opening and scanning', '%', '3', '1');
INSERT INTO `pricing` VALUES ('860', '2', 'additional_price_included_page_opening_scanning', '0.2', 'Additional Included pages for opening and scanning', '%', '3', '1');
INSERT INTO `pricing` VALUES ('861', '3', 'additional_price_included_page_opening_scanning', '0.2', 'Additional Included pages for opening and scanning', '%', '3', '1');
INSERT INTO `pricing` VALUES ('862', '1', 'custom_handling_import', '20', 'customs handling import ', '%', '3', '1');
INSERT INTO `pricing` VALUES ('863', '2', 'custom_handling_import', '20', 'customs handling import ', '%', '3', '1');
INSERT INTO `pricing` VALUES ('864', '3', 'custom_handling_import', '20', 'customs handling import ', '%', '3', '1');
INSERT INTO `pricing` VALUES ('865', '1', 'cash_payment_on_delivery_percentage', '10', 'Cash payment for item on delivery (percentage)', '%', '3', '1');
INSERT INTO `pricing` VALUES ('866', '2', 'cash_payment_on_delivery_percentage', '10', 'Cash payment for item on delivery (percentage)', '%', '3', '1');
INSERT INTO `pricing` VALUES ('867', '3', 'cash_payment_on_delivery_percentage', '10', 'Cash payment for item on delivery (percentage)', '%', '3', '1');
INSERT INTO `pricing` VALUES ('868', '1', 'cash_payment_on_delivery_mini_cost', '5', 'Cash payment for item on delivery (minimum cost)', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('869', '2', 'cash_payment_on_delivery_mini_cost', '5', 'Cash payment for item on delivery (minimum cost)', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('870', '3', 'cash_payment_on_delivery_mini_cost', '5', 'Cash payment for item on delivery (minimum cost)', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('871', '1', 'official_address_verification', '10', 'official address verification', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('872', '2', 'official_address_verification', '10', 'official address verification', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('873', '3', 'official_address_verification', '10', 'official address verification', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('874', '1', 'custom_declaration_outgoing_01', '59', 'Customs declaration outgoing (value >1000 EUR)', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('875', '2', 'custom_declaration_outgoing_01', '59', 'Customs declaration outgoing (value >1000 EUR)', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('876', '3', 'custom_declaration_outgoing_01', '59', 'Customs declaration outgoing (value >1000 EUR)', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('877', '1', 'custom_declaration_outgoing_02', '10', 'Customs declaration outgoing (value <1000 EUR)', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('878', '2', 'custom_declaration_outgoing_02', '10', 'Customs declaration outgoing (value <1000 EUR)', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('879', '3', 'custom_declaration_outgoing_02', '10', 'Customs declaration outgoing (value <1000 EUR)', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('880', '1', 'collect_shipping_plus', '20', 'Shipping collected to forwarding address (percentage on top of postal charge)', '%', '3', '1');
INSERT INTO `pricing` VALUES ('881', '2', 'collect_shipping_plus', '20', 'Shipping collected to forwarding address (percentage on top of postal charge)', '%', '3', '1');
INSERT INTO `pricing` VALUES ('882', '3', 'collect_shipping_plus', '20', 'Shipping collected to forwarding address (percentage on top of postal charge)', '%', '3', '1');
INSERT INTO `pricing` VALUES ('883', '1', 'pickup_charge', '50', 'Pickup charge (only with confirmed appointment)', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('884', '2', 'pickup_charge', '50', 'Pickup charge (only with confirmed appointment)', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('885', '3', 'pickup_charge', '50', 'Pickup charge (only with confirmed appointment)', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('886', '1', 'special_requests_charge_by_time', '60', 'Pickup charge (only with confirmed appointment)', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('887', '2', 'special_requests_charge_by_time', '60', 'Pickup charge (only with confirmed appointment)', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('888', '3', 'special_requests_charge_by_time', '60', 'Pickup charge (only with confirmed appointment)', 'EUR', '3', '1');
INSERT INTO `pricing` VALUES ('889', '1', 'paypal_transaction_fee', '3', 'Pickup charge (only with confirmed appointment)', '%', '3', '1');
INSERT INTO `pricing` VALUES ('890', '2', 'paypal_transaction_fee', '3', 'Pickup charge (only with confirmed appointment)', '%', '3', '1');
INSERT INTO `pricing` VALUES ('891', '3', 'paypal_transaction_fee', '3', 'Pickup charge (only with confirmed appointment)', '%', '3', '1');
