ALTER TABLE `customers`
	ADD COLUMN `deleted_by` INT(11) NULL DEFAULT NULL COMMENT '0:system| self: = customer_id | admin_user_id' AFTER `direct_access_expired`;
ALTER TABLE `invoice_summary_total_by_location`
	ADD COLUMN `number_of_account_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `number_of_postbox_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `number_of_item_received_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `number_of_envelope_scan_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `number_of_item_scan_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `number_of_item_forwarded_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `number_of_storage_item_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `number_of_new_registration_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `number_of_never_activated_deleted_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `number_of_manual_deleted_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `number_of_automatic_deleted_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `number_of_customers_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `free_postbox_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `free_postbox_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `private_postbox_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `private_postbox_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `business_postbox_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `business_postbox_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `free_incoming_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `free_incoming_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `private_incoming_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `private_incoming_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `business_incoming_item_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `business_incoming_item_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `free_envelope_scan_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `free_envelope_scan_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `private_envelope_scan_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `private_envelope_scan_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `business_envelope_scan_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `business_envelope_scan_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `free_item_scan_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `free_item_scan_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `private_item_scan_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `private_item_scan_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `business_item_scan_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `business_item_scan_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `free_additional_page_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `free_additional_page_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `private_additional_page_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `private_additional_page_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `business_additional_page_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `business_additional_page_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `fowarding_charge_postal_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `fowarding_charge_postal_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `fowarding_charge_fee_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `fowarding_charge_fee_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `free_storage_letter_quanity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `free_storage_letter_quanity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `private_storage_letter_quanity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `private_storage_letter_quanity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `business_storage_letter_quanity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `business_storage_letter_quanity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `free_storage_package_quanity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `free_storage_package_quanity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `private_storage_package_quanity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `private_storage_package_quanity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `business_storage_package_quanity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `business_storage_package_quanity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `custom_declaration_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `custom_declaration_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `cash_payment_fee_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `cash_payment_fee_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `custom_cost_import_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `custom_cost_import_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `import_custom_fee_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `import_custom_fee_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `address_verification_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `address_verification_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `special_service_fee_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `special_service_fee_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `peronsal_pickup_charge_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `peronsal_pickup_charge_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `paypal_transaction_fee_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `paypal_transaction_fee_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `other_local_invoice_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `other_local_invoice_quantity_share` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `creditnote_quantity` INT(11) NULL DEFAULT NULL,
	ADD COLUMN `creditnote_quantity_share` INT(11) NULL DEFAULT NULL;
	
	
=================================== 20161201-===========================
RENAME TABLE `invoice_summary_total_by_location` TO `report_by_location`;

CREATE TABLE `report_by_total` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`invoice_month` VARCHAR(8) NOT NULL COLLATE 'utf8_unicode_ci',
	`number_of_account` INT(11) NOT NULL,
	`number_of_postbox` INT(11) NOT NULL,
	`item_received` INT(11) NOT NULL,
	`envelope_scanned` INT(11) NOT NULL,
	`item_scanned` INT(11) NOT NULL,
	`item_forwarded` INT(11) NOT NULL,
	`item_on_storage` INT(11) NOT NULL,
	`new_registration` INT(11) NOT NULL,
	`never_activated_deleted` INT(11) NOT NULL,
	`manually_deleted` INT(11) NOT NULL,
	`automatically_deleted` INT(11) NOT NULL,
	`number_of_customer` INT(11) NOT NULL,
	`created_date` INT(11) NOT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
;

ALTER TABLE `report_by_location`
	ADD COLUMN `cash_expenditure_of_partner` DOUBLE NULL DEFAULT NULL AFTER `custom_declaration_outgoing_price_02_amount_share`;

ALTER TABLE `report_by_total`
	ADD COLUMN `cash_expenditure_of_partner` DOUBLE NOT NULL AFTER `number_of_customer`;

ALTER TABLE `report_by_location`
	ADD COLUMN `free_postboxes_netprice` DOUBLE NULL DEFAULT NULL AFTER `creditnote_quantity_share`,
	ADD COLUMN `private_postboxes_netprice` DOUBLE NULL DEFAULT NULL AFTER `free_postboxes_netprice`,
	ADD COLUMN `business_postboxes_netprice` DOUBLE NULL DEFAULT NULL AFTER `private_postboxes_netprice`,
	ADD COLUMN `incomming_items_free_netprice` DOUBLE NULL DEFAULT NULL AFTER `business_postboxes_netprice`,
	ADD COLUMN `incomming_items_private_netprice` DOUBLE NULL DEFAULT NULL AFTER `incomming_items_free_netprice`,
	ADD COLUMN `incomming_items_business_netprice` DOUBLE NULL DEFAULT NULL AFTER `incomming_items_private_netprice`,
	ADD COLUMN `envelope_scan_free_netprice` DOUBLE NULL DEFAULT NULL AFTER `incomming_items_business_netprice`,
	ADD COLUMN `envelope_scan_private_netprice` DOUBLE NULL DEFAULT NULL AFTER `envelope_scan_free_netprice`,
	ADD COLUMN `envelope_scan_business_netprice` DOUBLE NULL DEFAULT NULL AFTER `envelope_scan_private_netprice`,
	ADD COLUMN `item_scan_free_netprice` DOUBLE NULL DEFAULT NULL AFTER `envelope_scan_business_netprice`,
	ADD COLUMN `item_scan_private_netprice` DOUBLE NULL DEFAULT NULL AFTER `item_scan_free_netprice`,
	ADD COLUMN `item_scan_business_netprice` DOUBLE NULL DEFAULT NULL AFTER `item_scan_private_netprice`,
	ADD COLUMN `additional_pages_scanning_free_netprice` DOUBLE NULL DEFAULT NULL AFTER `item_scan_business_netprice`,
	ADD COLUMN `additional_pages_scanning_private_netprice` DOUBLE NULL DEFAULT NULL AFTER `additional_pages_scanning_free_netprice`,
	ADD COLUMN `additional_pages_scanning_business_netprice` DOUBLE NULL DEFAULT NULL AFTER `additional_pages_scanning_private_netprice`,
	ADD COLUMN `storing_letters_free_netprice` DOUBLE NULL DEFAULT NULL AFTER `additional_pages_scanning_business_netprice`,
	ADD COLUMN `storing_letters_private_netprice` DOUBLE NULL DEFAULT NULL AFTER `storing_letters_free_netprice`,
	ADD COLUMN `storing_letters_business_netprice` DOUBLE NULL DEFAULT NULL AFTER `storing_letters_private_netprice`,
	ADD COLUMN `storing_packages_free_netprice` DOUBLE NULL DEFAULT NULL AFTER `storing_letters_business_netprice`,
	ADD COLUMN `storing_packages_private_netprice` DOUBLE NULL DEFAULT NULL AFTER `storing_packages_free_netprice`,
	ADD COLUMN `storing_packages_business_netprice` DOUBLE NULL DEFAULT NULL AFTER `storing_packages_private_netprice`;
