

ALTER TABLE `report_by_partner`
	ADD COLUMN `customer_discount` VARCHAR(10) NULL DEFAULT NULL AFTER `duration_rev_share`,
	ADD COLUMN `commission_for_registration` DOUBLE NULL DEFAULT NULL AFTER `customer_discount`,
	ADD COLUMN `commission_for_activation` DOUBLE NULL DEFAULT NULL AFTER `commission_for_registration`,
	ADD COLUMN `duration_customer_discount` VARCHAR(10) NULL DEFAULT NULL AFTER `commission_for_activation`;

ALTER TABLE `report_by_partner`
	CHANGE COLUMN `rev_share` `rev_share` DOUBLE NULL DEFAULT NULL AFTER `creditnote_quantity`,
	CHANGE COLUMN `duration_rev_share` `duration_rev_share` DOUBLE NULL DEFAULT NULL AFTER `rev_share`,
	CHANGE COLUMN `customer_discount` `customer_discount` DOUBLE NULL DEFAULT NULL AFTER `duration_rev_share`,
	CHANGE COLUMN `duration_customer_discount` `duration_customer_discount` DOUBLE NULL DEFAULT NULL AFTER `commission_for_activation`;

ALTER TABLE `partner_customers`
	ADD COLUMN `customer_discount` DOUBLE NULL DEFAULT '0' AFTER `created_date`,
	ADD COLUMN `duration_customer_discount` DOUBLE NULL DEFAULT '0' AFTER `customer_discount`,
	ADD COLUMN `duration_rev_share` DOUBLE NULL DEFAULT '0' AFTER `duration_customer_discount`,
	ADD COLUMN `rev_share_ad` DOUBLE NULL DEFAULT '0' AFTER `duration_rev_share`,
	ADD COLUMN `comission_for_registration` DOUBLE NULL DEFAULT '0' AFTER `rev_share_ad`,
	ADD COLUMN `comission_for_activation` DOUBLE NULL DEFAULT '0' AFTER `comission_for_registration`;


ALTER TABLE `partner_customers`
	ADD COLUMN `end_flag` TINYINT NULL DEFAULT '0' AFTER `comission_for_activation`;


ALTER TABLE `partner_customers`
	ADD INDEX `key1` (`partner_id`, `customer_id`, `end_flag`);


DROP table report_by_partner;
CREATE TABLE `report_by_partner` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`partner_id` BIGINT(20) NULL DEFAULT 0 ,
	`invoice_month` VARCHAR(8) NULL DEFAULT NULL ,
	`free_postboxes_amount` DOUBLE NULL DEFAULT 0 ,
	`private_postboxes_amount` DOUBLE NULL DEFAULT 0 ,
	`business_postboxes_amount` DOUBLE NULL DEFAULT 0 ,
	`incomming_items_free_account` DOUBLE NULL DEFAULT 0 ,
	`incomming_items_private_account` DOUBLE NULL DEFAULT 0 ,
	`incomming_items_business_account` DOUBLE NULL DEFAULT 0 ,
	`envelope_scan_free_account` DOUBLE NULL DEFAULT 0 ,
	`envelope_scan_private_account` DOUBLE NULL DEFAULT 0 ,
	`envelope_scan_business_account` DOUBLE NULL DEFAULT 0 ,
	`item_scan_free_account` DOUBLE NULL DEFAULT 0 ,
	`item_scan_private_account` DOUBLE NULL DEFAULT 0 ,
	`item_scan_business_account` DOUBLE NULL DEFAULT 0 ,
	`storing_letters_free_account` DOUBLE NULL DEFAULT 0 ,
	`storing_letters_private_account` DOUBLE NULL DEFAULT 0 ,
	`storing_letters_business_account` DOUBLE NULL DEFAULT 0 ,
	`storing_packages_free_account` DOUBLE NULL DEFAULT 0 ,
	`storing_packages_private_account` DOUBLE NULL DEFAULT 0 ,
	`storing_packages_business_account` DOUBLE NULL DEFAULT 0 ,
	`forwarding_charges_postal` DOUBLE NULL DEFAULT 0 ,
	`forwarding_charges_fee` DOUBLE NULL DEFAULT 0 ,
	`cash_payment_for_item_delivery_amount` DOUBLE NULL DEFAULT 0 ,
	`cash_payment_free_for_item_delivery_amount` DOUBLE NULL DEFAULT 0 ,
	`customs_cost_import_amount` DOUBLE NULL DEFAULT 0 ,
	`customs_handling_fee_import_amount` DOUBLE NULL DEFAULT 0 ,
	`address_verification_amount` DOUBLE NULL DEFAULT 0 ,
	`special_service_fee_in_15min_intervalls_amount` DOUBLE NULL DEFAULT 0 ,
	`personal_pickup_charge_amount` DOUBLE NULL DEFAULT 0 ,
	`paypal_fee` DOUBLE NULL DEFAULT 0 ,
	`other_local_invoice` DOUBLE NULL DEFAULT 0 ,
	`credit_note_given` DOUBLE NULL DEFAULT 0 ,
	`net_total_invoice` DOUBLE NULL DEFAULT 0 ,
	`gross_total_invoice` DOUBLE NULL DEFAULT 0 ,
	`share_total_invoice` DOUBLE NULL DEFAULT 0 ,
	`invoice_type` VARCHAR(10) NULL DEFAULT NULL ,
	`additional_pages_scanning_free_amount` DOUBLE NULL DEFAULT 0 ,
	`additional_pages_scanning_private_amount` DOUBLE NULL DEFAULT 0 ,
	`additional_pages_scanning_business_amount` DOUBLE NULL DEFAULT 0 ,
	`custom_declaration_outgoing_price_01` DECIMAL(18,10) NULL DEFAULT 0 ,
	`custom_declaration_outgoing_price_02` DECIMAL(18,10) NULL DEFAULT 0 ,
	`number_of_account` INT(11) NULL DEFAULT 0 ,
	`number_of_postbox` INT(11) NULL DEFAULT 0 ,
	`number_of_item_received` INT(11) NULL DEFAULT 0 ,
	`number_of_envelope_scan` INT(11) NULL DEFAULT 0 ,
	`number_of_item_scan` INT(11) NULL DEFAULT 0 ,
	`number_of_item_forwarded` INT(11) NULL DEFAULT 0 ,
	`number_of_storage_item` INT(11) NULL DEFAULT 0 ,
	`number_of_new_registration` INT(11) NULL DEFAULT 0 ,
	`number_of_never_activated_deleted` INT(11) NULL DEFAULT 0 ,
	`number_of_manual_deleted` INT(11) NULL DEFAULT 0 ,
	`number_of_automatic_deleted` INT(11) NULL DEFAULT 0 ,
	`number_of_customers` INT(11) NULL DEFAULT 0 ,
	`free_postbox_quantity` INT(11) NULL DEFAULT 0 ,
	`private_postbox_quantity` INT(11) NULL DEFAULT 0 ,
	`business_postbox_quantity` INT(11) NULL DEFAULT 0 ,
	`free_incoming_quantity` INT(11) NULL DEFAULT 0 ,
	`private_incoming_quantity` INT(11) NULL DEFAULT 0 ,
	`business_incoming_item_quantity` INT(11) NULL DEFAULT 0 ,
	`free_envelope_scan_quantity` INT(11) NULL DEFAULT 0 ,
	`private_envelope_scan_quantity` INT(11) NULL DEFAULT 0 ,
	`business_envelope_scan_quantity` INT(11) NULL DEFAULT 0 ,
	`free_item_scan_quantity` INT(11) NULL DEFAULT 0 ,
	`private_item_scan_quantity` INT(11) NULL DEFAULT 0 ,
	`business_item_scan_quantity` INT(11) NULL DEFAULT 0 ,
	`free_additional_page_quantity` INT(11) NULL DEFAULT 0 ,
	`private_additional_page_quantity` INT(11) NULL DEFAULT 0 ,
	`business_additional_page_quantity` INT(11) NULL DEFAULT 0 ,
	`fowarding_charge_postal_quantity` INT(11) NULL DEFAULT 0 ,
	`fowarding_charge_fee_quantity` INT(11) NULL DEFAULT 0 ,
	`free_storage_letter_quanity` INT(11) NULL DEFAULT 0 ,
	`private_storage_letter_quanity` INT(11) NULL DEFAULT 0 ,
	`business_storage_letter_quanity` INT(11) NULL DEFAULT 0 ,
	`free_storage_package_quanity` INT(11) NULL DEFAULT 0 ,
	`private_storage_package_quanity` INT(11) NULL DEFAULT 0 ,
	`business_storage_package_quanity` INT(11) NULL DEFAULT 0 ,
	`custom_declaration_quantity` INT(11) NULL DEFAULT 0 ,
	`cash_payment_fee_quantity` INT(11) NULL DEFAULT 0 ,
	`custom_cost_import_quantity` INT(11) NULL DEFAULT 0 ,
	`import_custom_fee_quantity` INT(11) NULL DEFAULT 0 ,
	`address_verification_quantity` INT(11) NULL DEFAULT 0 ,
	`special_service_fee_quantity` INT(11) NULL DEFAULT 0 ,
	`peronsal_pickup_charge_quantity` INT(11) NULL DEFAULT 0 ,
	`paypal_transaction_fee_quantity` INT(11) NULL DEFAULT 0 ,
	`other_local_invoice_quantity` INT(11) NULL DEFAULT 0 ,
	`creditnote_quantity` INT(11) NULL DEFAULT 0 ,
	`rev_share` DOUBLE NULL DEFAULT 0 ,
	`duration_rev_share` DOUBLE NULL DEFAULT 0 ,
	`customer_discount` DOUBLE NULL DEFAULT 0 ,
	`commission_for_registration` DOUBLE NULL DEFAULT 0 ,
	`commission_for_activation` DOUBLE NULL DEFAULT 0 ,
	`duration_customer_discount` DOUBLE NULL DEFAULT 0 ,
	`created_date` INT(11) NULL DEFAULT 0 ,
	`free_postboxes_amount_share` DOUBLE NULL DEFAULT 0 ,
	`private_postboxes_amount_share` DOUBLE NULL DEFAULT 0 ,
	`business_postboxes_amount_share` DOUBLE NULL DEFAULT 0 ,
	`incomming_items_free_account_share` DOUBLE NULL DEFAULT 0 ,
	`incomming_items_private_account_share` DOUBLE NULL DEFAULT 0 ,
	`incomming_items_business_account_share` DOUBLE NULL DEFAULT 0 ,
	`envelope_scan_free_account_share` DOUBLE NULL DEFAULT 0 ,
	`envelope_scan_private_account_share` DOUBLE NULL DEFAULT 0 ,
	`envelope_scan_business_account_share` DOUBLE NULL DEFAULT 0 ,
	`item_scan_free_account_share` DOUBLE NULL DEFAULT 0 ,
	`item_scan_private_account_share` DOUBLE NULL DEFAULT 0 ,
	`item_scan_business_account_share` DOUBLE NULL DEFAULT 0 ,
	`storing_letters_free_account_share` DOUBLE NULL DEFAULT 0 ,
	`storing_letters_private_account_share` DOUBLE NULL DEFAULT 0 ,
	`storing_letters_business_account_share` DOUBLE NULL DEFAULT 0 ,
	`storing_packages_free_account_share` DOUBLE NULL DEFAULT 0 ,
	`storing_packages_private_account_share` DOUBLE NULL DEFAULT 0 ,
	`storing_packages_business_account_share` DOUBLE NULL DEFAULT 0 ,
	`forwarding_charges_postal_share` DOUBLE NULL DEFAULT 0 ,
	`forwarding_charges_fee_share` DOUBLE NULL DEFAULT 0 ,
	`cash_payment_for_item_delivery_amount_share` DOUBLE NULL DEFAULT 0 ,
	`cash_payment_free_for_item_delivery_amount_share` DOUBLE NULL DEFAULT 0 ,
	`customs_cost_import_amount_share` DOUBLE NULL DEFAULT 0 ,
	`customs_handling_fee_import_amount_share` DOUBLE NULL DEFAULT 0 ,
	`address_verification_amount_share` DOUBLE NULL DEFAULT 0 ,
	`special_service_fee_in_15min_intervalls_amount_share` DOUBLE NULL DEFAULT 0 ,
	`personal_pickup_charge_amount_share` DOUBLE NULL DEFAULT 0 ,
	`paypal_fee_share` DOUBLE NULL DEFAULT 0 ,
	`other_local_invoice_share` DOUBLE NULL DEFAULT 0 ,
	`credit_note_given_share` DOUBLE NULL DEFAULT 0 ,
	`free_postboxes_amount_discount` DOUBLE NULL DEFAULT 0 ,
	`private_postboxes_amount_discount` DOUBLE NULL DEFAULT 0 ,
	`business_postboxes_amount_discount` DOUBLE NULL DEFAULT 0 ,
	`incomming_items_free_account_discount` DOUBLE NULL DEFAULT 0 ,
	`incomming_items_private_account_discount` DOUBLE NULL DEFAULT 0 ,
	`incomming_items_business_account_discount` DOUBLE NULL DEFAULT 0 ,
	`envelope_scan_free_account_discount` DOUBLE NULL DEFAULT 0 ,
	`envelope_scan_private_account_discount` DOUBLE NULL DEFAULT 0 ,
	`envelope_scan_business_account_discount` DOUBLE NULL DEFAULT 0 ,
	`item_scan_free_account_discount` DOUBLE NULL DEFAULT 0 ,
	`item_scan_private_account_discount` DOUBLE NULL DEFAULT 0 ,
	`item_scan_business_account_discount` DOUBLE NULL DEFAULT 0 ,
	`storing_letters_free_account_discount` DOUBLE NULL DEFAULT 0 ,
	`storing_letters_private_account_discount` DOUBLE NULL DEFAULT 0 ,
	`storing_letters_business_account_discount` DOUBLE NULL DEFAULT 0 ,
	`storing_packages_free_account_discount` DOUBLE NULL DEFAULT 0 ,
	`storing_packages_private_account_discount` DOUBLE NULL DEFAULT 0 ,
	`storing_packages_business_account_discount` DOUBLE NULL DEFAULT 0 ,
	`forwarding_charges_postal_discount` DOUBLE NULL DEFAULT 0 ,
	`forwarding_charges_fee_discount` DOUBLE NULL DEFAULT 0 ,
	`cash_payment_for_item_delivery_amount_discount` DOUBLE NULL DEFAULT 0 ,
	`cash_payment_free_for_item_delivery_amount_discount` DOUBLE NULL DEFAULT 0 ,
	`customs_cost_import_amount_discount` DOUBLE NULL DEFAULT 0 ,
	`customs_handling_fee_import_amount_discount` DOUBLE NULL DEFAULT 0 ,
	`address_verification_amount_discount` DOUBLE NULL DEFAULT 0 ,
	`special_service_fee_in_15min_intervalls_amount_discount` DOUBLE NULL DEFAULT 0 ,
	`personal_pickup_charge_amount_discount` DOUBLE NULL DEFAULT 0 ,
	`paypal_fee_discount` DOUBLE NULL DEFAULT 0 ,
	`other_local_invoice_discount` DOUBLE NULL DEFAULT 0 ,
	`credit_note_given_discount` DOUBLE NULL DEFAULT 0 ,
	`additional_pages_scanning_free_amount_discount` DOUBLE NULL DEFAULT 0 ,
	`additional_pages_scanning_private_amount_discount` DOUBLE NULL DEFAULT 0 ,
	`additional_pages_scanning_business_amount_discount` DOUBLE NULL DEFAULT 0 ,
	`additional_pages_scanning_free_amount_share` DOUBLE NULL DEFAULT 0 ,
	`additional_pages_scanning_private_amount_share` DOUBLE NULL DEFAULT 0 ,
	`additional_pages_scanning_business_amount_share` DOUBLE NULL DEFAULT 0 ,
	`custom_declaration_outgoing_price_01_discount` DECIMAL(18,10) NULL DEFAULT 0 ,
	`custom_declaration_outgoing_price_02_discount` DECIMAL(18,10) NULL DEFAULT 0 ,
	`custom_declaration_outgoing_price_01_share` DECIMAL(18,10) NULL DEFAULT 0 ,
	`custom_declaration_outgoing_price_02_share` DECIMAL(18,10) NULL DEFAULT 0 ,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;



