ALTER TABLE country
ADD country_code_3 varchar(3);

UPDATE country SET country_code_3 = '---' WHERE country_code = 'XK';
UPDATE country SET country_code_3 = 'ABW' WHERE country_code = 'AW';
UPDATE country SET country_code_3 = 'AFG' WHERE country_code = 'AF';
UPDATE country SET country_code_3 = 'AGO' WHERE country_code = 'AO';
UPDATE country SET country_code_3 = 'AIA' WHERE country_code = 'AI';
UPDATE country SET country_code_3 = 'ALA' WHERE country_code = 'AX';
UPDATE country SET country_code_3 = 'ALB' WHERE country_code = 'AL';
UPDATE country SET country_code_3 = 'AND' WHERE country_code = 'AD';
UPDATE country SET country_code_3 = 'ARE' WHERE country_code = 'AE';
UPDATE country SET country_code_3 = 'ARG' WHERE country_code = 'AR';
UPDATE country SET country_code_3 = 'ARM' WHERE country_code = 'AM';
UPDATE country SET country_code_3 = 'ASM' WHERE country_code = 'AS';
UPDATE country SET country_code_3 = 'ATA' WHERE country_code = 'AQ';
UPDATE country SET country_code_3 = 'ATF' WHERE country_code = 'TF';
UPDATE country SET country_code_3 = 'ATG' WHERE country_code = 'AG';
UPDATE country SET country_code_3 = 'AUS' WHERE country_code = 'AU';
UPDATE country SET country_code_3 = 'AUT' WHERE country_code = 'AT';
UPDATE country SET country_code_3 = 'AZE' WHERE country_code = 'AZ';
UPDATE country SET country_code_3 = 'BDI' WHERE country_code = 'BI';
UPDATE country SET country_code_3 = 'BEL' WHERE country_code = 'BE';
UPDATE country SET country_code_3 = 'BEN' WHERE country_code = 'BJ';
UPDATE country SET country_code_3 = 'BES' WHERE country_code = 'BQ';
UPDATE country SET country_code_3 = 'BFA' WHERE country_code = 'BF';
UPDATE country SET country_code_3 = 'BGD' WHERE country_code = 'BD';
UPDATE country SET country_code_3 = 'BGR' WHERE country_code = 'BG';
UPDATE country SET country_code_3 = 'BHR' WHERE country_code = 'BH';
UPDATE country SET country_code_3 = 'BHS' WHERE country_code = 'BS';
UPDATE country SET country_code_3 = 'BIH' WHERE country_code = 'BA';
UPDATE country SET country_code_3 = 'BLM' WHERE country_code = 'BL';
UPDATE country SET country_code_3 = 'BLR' WHERE country_code = 'BY';
UPDATE country SET country_code_3 = 'BLZ' WHERE country_code = 'BZ';
UPDATE country SET country_code_3 = 'BMU' WHERE country_code = 'BM';
UPDATE country SET country_code_3 = 'BOL' WHERE country_code = 'BO';
UPDATE country SET country_code_3 = 'BRA' WHERE country_code = 'BR';
UPDATE country SET country_code_3 = 'BRB' WHERE country_code = 'BB';
UPDATE country SET country_code_3 = 'BRN' WHERE country_code = 'BN';
UPDATE country SET country_code_3 = 'BTN' WHERE country_code = 'BT';
UPDATE country SET country_code_3 = 'BVT' WHERE country_code = 'BV';
UPDATE country SET country_code_3 = 'BWA' WHERE country_code = 'BW';
UPDATE country SET country_code_3 = 'CAF' WHERE country_code = 'CF';
UPDATE country SET country_code_3 = 'CAN' WHERE country_code = 'CA';
UPDATE country SET country_code_3 = 'CCK' WHERE country_code = 'CC';
UPDATE country SET country_code_3 = 'CHE' WHERE country_code = 'CH';
UPDATE country SET country_code_3 = 'CHL' WHERE country_code = 'CL';
UPDATE country SET country_code_3 = 'CHN' WHERE country_code = 'CN';
UPDATE country SET country_code_3 = 'CIV' WHERE country_code = 'CI';
UPDATE country SET country_code_3 = 'CMR' WHERE country_code = 'CM';
UPDATE country SET country_code_3 = 'COD' WHERE country_code = 'CD';
UPDATE country SET country_code_3 = 'COG' WHERE country_code = 'CG';
UPDATE country SET country_code_3 = 'COK' WHERE country_code = 'CK';
UPDATE country SET country_code_3 = 'COL' WHERE country_code = 'CO';
UPDATE country SET country_code_3 = 'COM' WHERE country_code = 'KM';
UPDATE country SET country_code_3 = 'CPV' WHERE country_code = 'CV';
UPDATE country SET country_code_3 = 'CRI' WHERE country_code = 'CR';
UPDATE country SET country_code_3 = 'CUB' WHERE country_code = 'CU';
UPDATE country SET country_code_3 = 'CUW' WHERE country_code = 'CW';
UPDATE country SET country_code_3 = 'CXR' WHERE country_code = 'CX';
UPDATE country SET country_code_3 = 'CYM' WHERE country_code = 'KY';
UPDATE country SET country_code_3 = 'CYP' WHERE country_code = 'CY';
UPDATE country SET country_code_3 = 'CZE' WHERE country_code = 'CZ';
UPDATE country SET country_code_3 = 'DEU' WHERE country_code = 'DE';
UPDATE country SET country_code_3 = 'DJI' WHERE country_code = 'DJ';
UPDATE country SET country_code_3 = 'DMA' WHERE country_code = 'DM';
UPDATE country SET country_code_3 = 'DNK' WHERE country_code = 'DK';
UPDATE country SET country_code_3 = 'DOM' WHERE country_code = 'DO';
UPDATE country SET country_code_3 = 'DZA' WHERE country_code = 'DZ';
UPDATE country SET country_code_3 = 'ECU' WHERE country_code = 'EC';
UPDATE country SET country_code_3 = 'EGY' WHERE country_code = 'EG';
UPDATE country SET country_code_3 = 'ERI' WHERE country_code = 'ER';
UPDATE country SET country_code_3 = 'ESH' WHERE country_code = 'EH';
UPDATE country SET country_code_3 = 'ESP' WHERE country_code = 'ES';
UPDATE country SET country_code_3 = 'EST' WHERE country_code = 'EE';
UPDATE country SET country_code_3 = 'ETH' WHERE country_code = 'ET';
UPDATE country SET country_code_3 = 'EUR' WHERE country_code = 'EUR';
UPDATE country SET country_code_3 = 'FIN' WHERE country_code = 'FI';
UPDATE country SET country_code_3 = 'FJI' WHERE country_code = 'FJ';
UPDATE country SET country_code_3 = 'FLK' WHERE country_code = 'FK';
UPDATE country SET country_code_3 = 'FRA' WHERE country_code = 'FR';
UPDATE country SET country_code_3 = 'FRO' WHERE country_code = 'FO';
UPDATE country SET country_code_3 = 'FSM' WHERE country_code = 'FM';
UPDATE country SET country_code_3 = 'GAB' WHERE country_code = 'GA';
UPDATE country SET country_code_3 = 'GBR' WHERE country_code = 'GB';
UPDATE country SET country_code_3 = 'GEO' WHERE country_code = 'GE';
UPDATE country SET country_code_3 = 'GGY' WHERE country_code = 'GG';
UPDATE country SET country_code_3 = 'GHA' WHERE country_code = 'GH';
UPDATE country SET country_code_3 = 'GIB' WHERE country_code = 'GI';
UPDATE country SET country_code_3 = 'GIN' WHERE country_code = 'GN';
UPDATE country SET country_code_3 = 'GLP' WHERE country_code = 'GP';
UPDATE country SET country_code_3 = 'GMB' WHERE country_code = 'GM';
UPDATE country SET country_code_3 = 'GNB' WHERE country_code = 'GW';
UPDATE country SET country_code_3 = 'GNQ' WHERE country_code = 'GQ';
UPDATE country SET country_code_3 = 'GRC' WHERE country_code = 'GR';
UPDATE country SET country_code_3 = 'GRD' WHERE country_code = 'GD';
UPDATE country SET country_code_3 = 'GRL' WHERE country_code = 'GL';
UPDATE country SET country_code_3 = 'GTM' WHERE country_code = 'GT';
UPDATE country SET country_code_3 = 'GUF' WHERE country_code = 'GF';
UPDATE country SET country_code_3 = 'GUM' WHERE country_code = 'GU';
UPDATE country SET country_code_3 = 'GUY' WHERE country_code = 'GY';
UPDATE country SET country_code_3 = 'HKG' WHERE country_code = 'HK';
UPDATE country SET country_code_3 = 'HMD' WHERE country_code = 'HM';
UPDATE country SET country_code_3 = 'HND' WHERE country_code = 'HN';
UPDATE country SET country_code_3 = 'HRV' WHERE country_code = 'HR';
UPDATE country SET country_code_3 = 'HTI' WHERE country_code = 'HT';
UPDATE country SET country_code_3 = 'HUN' WHERE country_code = 'HU';
UPDATE country SET country_code_3 = 'IDN' WHERE country_code = 'ID';
UPDATE country SET country_code_3 = 'IMN' WHERE country_code = 'IM';
UPDATE country SET country_code_3 = 'IND' WHERE country_code = 'IN';
UPDATE country SET country_code_3 = 'IOT' WHERE country_code = 'IO';
UPDATE country SET country_code_3 = 'IRL' WHERE country_code = 'IE';
UPDATE country SET country_code_3 = 'IRN' WHERE country_code = 'IR';
UPDATE country SET country_code_3 = 'IRQ' WHERE country_code = 'IQ';
UPDATE country SET country_code_3 = 'ISL' WHERE country_code = 'IS';
UPDATE country SET country_code_3 = 'ISR' WHERE country_code = 'IL';
UPDATE country SET country_code_3 = 'ITA' WHERE country_code = 'IT';
UPDATE country SET country_code_3 = 'JAM' WHERE country_code = 'JM';
UPDATE country SET country_code_3 = 'JEY' WHERE country_code = 'JE';
UPDATE country SET country_code_3 = 'JOR' WHERE country_code = 'JO';
UPDATE country SET country_code_3 = 'JPN' WHERE country_code = 'JP';
UPDATE country SET country_code_3 = 'KAZ' WHERE country_code = 'KZ';
UPDATE country SET country_code_3 = 'KEN' WHERE country_code = 'KE';
UPDATE country SET country_code_3 = 'KGZ' WHERE country_code = 'KG';
UPDATE country SET country_code_3 = 'KHM' WHERE country_code = 'KH';
UPDATE country SET country_code_3 = 'KIR' WHERE country_code = 'KI';
UPDATE country SET country_code_3 = 'KNA' WHERE country_code = 'KN';
UPDATE country SET country_code_3 = 'KOR' WHERE country_code = 'KR';
UPDATE country SET country_code_3 = 'KWT' WHERE country_code = 'KW';
UPDATE country SET country_code_3 = 'LAO' WHERE country_code = 'LA';
UPDATE country SET country_code_3 = 'LBN' WHERE country_code = 'LB';
UPDATE country SET country_code_3 = 'LBR' WHERE country_code = 'LR';
UPDATE country SET country_code_3 = 'LBY' WHERE country_code = 'LY';
UPDATE country SET country_code_3 = 'LCA' WHERE country_code = 'LC';
UPDATE country SET country_code_3 = 'LIE' WHERE country_code = 'LI';
UPDATE country SET country_code_3 = 'LKA' WHERE country_code = 'LK';
UPDATE country SET country_code_3 = 'LSO' WHERE country_code = 'LS';
UPDATE country SET country_code_3 = 'LTU' WHERE country_code = 'LT';
UPDATE country SET country_code_3 = 'LUX' WHERE country_code = 'LU';
UPDATE country SET country_code_3 = 'LVA' WHERE country_code = 'LV';
UPDATE country SET country_code_3 = 'MAC' WHERE country_code = 'MO';
UPDATE country SET country_code_3 = 'MAF' WHERE country_code = 'MF';
UPDATE country SET country_code_3 = 'MAR' WHERE country_code = 'MA';
UPDATE country SET country_code_3 = 'MCO' WHERE country_code = 'MC';
UPDATE country SET country_code_3 = 'MDA' WHERE country_code = 'MD';
UPDATE country SET country_code_3 = 'MDG' WHERE country_code = 'MG';
UPDATE country SET country_code_3 = 'MDV' WHERE country_code = 'MV';
UPDATE country SET country_code_3 = 'MEX' WHERE country_code = 'MX';
UPDATE country SET country_code_3 = 'MHL' WHERE country_code = 'MH';
UPDATE country SET country_code_3 = 'MKD' WHERE country_code = 'MK';
UPDATE country SET country_code_3 = 'MLI' WHERE country_code = 'ML';
UPDATE country SET country_code_3 = 'MLT' WHERE country_code = 'MT';
UPDATE country SET country_code_3 = 'MMR' WHERE country_code = 'MM';
UPDATE country SET country_code_3 = 'MNE' WHERE country_code = 'ME';
UPDATE country SET country_code_3 = 'MNG' WHERE country_code = 'MN';
UPDATE country SET country_code_3 = 'MNP' WHERE country_code = 'MP';
UPDATE country SET country_code_3 = 'MOZ' WHERE country_code = 'MZ';
UPDATE country SET country_code_3 = 'MRT' WHERE country_code = 'MR';
UPDATE country SET country_code_3 = 'MSR' WHERE country_code = 'MS';
UPDATE country SET country_code_3 = 'MTQ' WHERE country_code = 'MQ';
UPDATE country SET country_code_3 = 'MUS' WHERE country_code = 'MU';
UPDATE country SET country_code_3 = 'MWI' WHERE country_code = 'MW';
UPDATE country SET country_code_3 = 'MYS' WHERE country_code = 'MY';
UPDATE country SET country_code_3 = 'MYT' WHERE country_code = 'YT';
UPDATE country SET country_code_3 = 'NAM' WHERE country_code = 'NA';
UPDATE country SET country_code_3 = 'NCL' WHERE country_code = 'NC';
UPDATE country SET country_code_3 = 'NER' WHERE country_code = 'NE';
UPDATE country SET country_code_3 = 'NFK' WHERE country_code = 'NF';
UPDATE country SET country_code_3 = 'NGA' WHERE country_code = 'NG';
UPDATE country SET country_code_3 = 'NIC' WHERE country_code = 'NI';
UPDATE country SET country_code_3 = 'NIU' WHERE country_code = 'NU';
UPDATE country SET country_code_3 = 'NLD' WHERE country_code = 'NL';
UPDATE country SET country_code_3 = 'NOR' WHERE country_code = 'NO';
UPDATE country SET country_code_3 = 'NPL' WHERE country_code = 'NP';
UPDATE country SET country_code_3 = 'NRU' WHERE country_code = 'NR';
UPDATE country SET country_code_3 = 'NZL' WHERE country_code = 'NZ';
UPDATE country SET country_code_3 = 'OMN' WHERE country_code = 'OM';
UPDATE country SET country_code_3 = 'PAK' WHERE country_code = 'PK';
UPDATE country SET country_code_3 = 'PAN' WHERE country_code = 'PA';
UPDATE country SET country_code_3 = 'PCN' WHERE country_code = 'PN';
UPDATE country SET country_code_3 = 'PER' WHERE country_code = 'PE';
UPDATE country SET country_code_3 = 'PHL' WHERE country_code = 'PH';
UPDATE country SET country_code_3 = 'PLW' WHERE country_code = 'PW';
UPDATE country SET country_code_3 = 'PNG' WHERE country_code = 'PG';
UPDATE country SET country_code_3 = 'POL' WHERE country_code = 'PL';
UPDATE country SET country_code_3 = 'PRI' WHERE country_code = 'PR';
UPDATE country SET country_code_3 = 'PRK' WHERE country_code = 'KP';
UPDATE country SET country_code_3 = 'PRT' WHERE country_code = 'PT';
UPDATE country SET country_code_3 = 'PRY' WHERE country_code = 'PY';
UPDATE country SET country_code_3 = 'PSE' WHERE country_code = 'PS';
UPDATE country SET country_code_3 = 'PYF' WHERE country_code = 'PF';
UPDATE country SET country_code_3 = 'QAT' WHERE country_code = 'QA';
UPDATE country SET country_code_3 = 'REU' WHERE country_code = 'RE';
UPDATE country SET country_code_3 = 'ROU' WHERE country_code = 'RO';
UPDATE country SET country_code_3 = 'RUS' WHERE country_code = 'RU';
UPDATE country SET country_code_3 = 'RWA' WHERE country_code = 'RW';
UPDATE country SET country_code_3 = 'SAU' WHERE country_code = 'SA';
UPDATE country SET country_code_3 = 'SDN' WHERE country_code = 'SD';
UPDATE country SET country_code_3 = 'SEN' WHERE country_code = 'SN';
UPDATE country SET country_code_3 = 'SGP' WHERE country_code = 'SG';
UPDATE country SET country_code_3 = 'SGS' WHERE country_code = 'GS';
UPDATE country SET country_code_3 = 'SHN' WHERE country_code = 'SH';
UPDATE country SET country_code_3 = 'SJM' WHERE country_code = 'SJ';
UPDATE country SET country_code_3 = 'SLB' WHERE country_code = 'SB';
UPDATE country SET country_code_3 = 'SLE' WHERE country_code = 'SL';
UPDATE country SET country_code_3 = 'SLV' WHERE country_code = 'SV';
UPDATE country SET country_code_3 = 'SMR' WHERE country_code = 'SM';
UPDATE country SET country_code_3 = 'SOM' WHERE country_code = 'SO';
UPDATE country SET country_code_3 = 'SPM' WHERE country_code = 'PM';
UPDATE country SET country_code_3 = 'SRB' WHERE country_code = 'RS';
UPDATE country SET country_code_3 = 'SSD' WHERE country_code = 'SS';
UPDATE country SET country_code_3 = 'STP' WHERE country_code = 'ST';
UPDATE country SET country_code_3 = 'SUR' WHERE country_code = 'SR';
UPDATE country SET country_code_3 = 'SVK' WHERE country_code = 'SK';
UPDATE country SET country_code_3 = 'SVN' WHERE country_code = 'SI';
UPDATE country SET country_code_3 = 'SWE' WHERE country_code = 'SE';
UPDATE country SET country_code_3 = 'SWZ' WHERE country_code = 'SZ';
UPDATE country SET country_code_3 = 'SXM' WHERE country_code = 'SX';
UPDATE country SET country_code_3 = 'SYC' WHERE country_code = 'SC';
UPDATE country SET country_code_3 = 'SYR' WHERE country_code = 'SY';
UPDATE country SET country_code_3 = 'TCA' WHERE country_code = 'TC';
UPDATE country SET country_code_3 = 'TCD' WHERE country_code = 'TD';
UPDATE country SET country_code_3 = 'TGO' WHERE country_code = 'TG';
UPDATE country SET country_code_3 = 'THA' WHERE country_code = 'TH';
UPDATE country SET country_code_3 = 'TJK' WHERE country_code = 'TJ';
UPDATE country SET country_code_3 = 'TKL' WHERE country_code = 'TK';
UPDATE country SET country_code_3 = 'TKM' WHERE country_code = 'TM';
UPDATE country SET country_code_3 = 'TLS' WHERE country_code = 'TL';
UPDATE country SET country_code_3 = 'TON' WHERE country_code = 'TO';
UPDATE country SET country_code_3 = 'TTO' WHERE country_code = 'TT';
UPDATE country SET country_code_3 = 'TUN' WHERE country_code = 'TN';
UPDATE country SET country_code_3 = 'TUR' WHERE country_code = 'TR';
UPDATE country SET country_code_3 = 'TUV' WHERE country_code = 'TV';
UPDATE country SET country_code_3 = 'TWN' WHERE country_code = 'TW';
UPDATE country SET country_code_3 = 'TZA' WHERE country_code = 'TZ';
UPDATE country SET country_code_3 = 'UGA' WHERE country_code = 'UG';
UPDATE country SET country_code_3 = 'UKR' WHERE country_code = 'UA';
UPDATE country SET country_code_3 = 'UMI' WHERE country_code = 'UM';
UPDATE country SET country_code_3 = 'URY' WHERE country_code = 'UY';
UPDATE country SET country_code_3 = 'USA' WHERE country_code = 'US';
UPDATE country SET country_code_3 = 'UZB' WHERE country_code = 'UZ';
UPDATE country SET country_code_3 = 'VAT' WHERE country_code = 'VA';
UPDATE country SET country_code_3 = 'VCT' WHERE country_code = 'VC';
UPDATE country SET country_code_3 = 'VEN' WHERE country_code = 'VE';
UPDATE country SET country_code_3 = 'VGB' WHERE country_code = 'VG';
UPDATE country SET country_code_3 = 'VIR' WHERE country_code = 'VI';
UPDATE country SET country_code_3 = 'VNM' WHERE country_code = 'VN';
UPDATE country SET country_code_3 = 'VUT' WHERE country_code = 'VU';
UPDATE country SET country_code_3 = 'WLF' WHERE country_code = 'WF';
UPDATE country SET country_code_3 = 'WSM' WHERE country_code = 'WS';
UPDATE country SET country_code_3 = 'YEM' WHERE country_code = 'YE';
UPDATE country SET country_code_3 = 'ZAF' WHERE country_code = 'ZA';
UPDATE country SET country_code_3 = 'ZMB' WHERE country_code = 'ZM';
UPDATE country SET country_code_3 = 'ZWE' WHERE country_code = 'ZW';



-- State Table courtesy statetable.com

CREATE TABLE state (id integer, name varchar(255), abbreviation varchar(255), country varchar(255), type varchar(255), sort integer, status varchar(255), occupied varchar(255), notes varchar(255), fips_state varchar(255), assoc_press varchar(255), standard_federal_region varchar(255), census_region varchar(255), census_region_name varchar(255), census_division varchar(255), census_division_name varchar(255), circuit_court varchar(255));
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('1','Alabama','AL','USA','state','10','current','occupied','','1','Ala.','IV','3','South','6','East South Central','11');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('2','Alaska','AK','USA','state','10','current','occupied','','2','Alaska','X','4','West','9','Pacific','9');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('3','Arizona','AZ','USA','state','10','current','occupied','','4','Ariz.','IX','4','West','8','Mountain','9');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('4','Arkansas','AR','USA','state','10','current','occupied','','5','Ark.','VI','3','South','7','West South Central','8');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('5','California','CA','USA','state','10','current','occupied','','6','Calif.','IX','4','West','9','Pacific','9');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('6','Colorado','CO','USA','state','10','current','occupied','','8','Colo.','VIII','4','West','8','Mountain','10');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('7','Connecticut','CT','USA','state','10','current','occupied','','9','Conn.','I','1','Northeast','1','New England','2');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('8','Delaware','DE','USA','state','10','current','occupied','','10','Del.','III','3','South','5','South Atlantic','3');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('9','Florida','FL','USA','state','10','current','occupied','','12','Fla.','IV','3','South','5','South Atlantic','11');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('10','Georgia','GA','USA','state','10','current','occupied','','13','Ga.','IV','3','South','5','South Atlantic','11');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('11','Hawaii','HI','USA','state','10','current','occupied','','15','Hawaii','IX','4','West','9','Pacific','9');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('12','Idaho','ID','USA','state','10','current','occupied','','16','Idaho','X','4','West','8','Mountain','9');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('13','Illinois','IL','USA','state','10','current','occupied','','17','Ill.','V','2','Midwest','3','East North Central','7');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('14','Indiana','IN','USA','state','10','current','occupied','','18','Ind.','V','2','Midwest','3','East North Central','7');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('15','Iowa','IA','USA','state','10','current','occupied','','19','Iowa','VII','2','Midwest','4','West North Central','8');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('16','Kansas','KS','USA','state','10','current','occupied','','20','Kan.','VII','2','Midwest','4','West North Central','10');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('17','Kentucky','KY','USA','state','10','current','occupied','','21','Ky.','IV','3','South','6','East South Central','6');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('18','Louisiana','LA','USA','state','10','current','occupied','','22','La.','VI','3','South','7','West South Central','5');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('19','Maine','ME','USA','state','10','current','occupied','','23','Maine','I','1','Northeast','1','New England','1');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('20','Maryland','MD','USA','state','10','current','occupied','','24','Md.','III','3','South','5','South Atlantic','4');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('21','Massachusetts','MA','USA','state','10','current','occupied','','25','Mass.','I','1','Northeast','1','New England','1');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('22','Michigan','MI','USA','state','10','current','occupied','','26','Mich.','V','2','Midwest','3','East North Central','6');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('23','Minnesota','MN','USA','state','10','current','occupied','','27','Minn.','V','2','Midwest','4','West North Central','8');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('24','Mississippi','MS','USA','state','10','current','occupied','','28','Miss.','IV','3','South','6','East South Central','5');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('25','Missouri','MO','USA','state','10','current','occupied','','29','Mo.','VII','2','Midwest','4','West North Central','8');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('26','Montana','MT','USA','state','10','current','occupied','','30','Mont.','VIII','4','West','8','Mountain','9');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('27','Nebraska','NE','USA','state','10','current','occupied','','31','Neb.','VII','2','Midwest','4','West North Central','8');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('28','Nevada','NV','USA','state','10','current','occupied','','32','Nev.','IX','4','West','8','Mountain','9');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('29','New Hampshire','NH','USA','state','10','current','occupied','','33','N.H.','I','1','Northeast','1','New England','1');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('30','New Jersey','NJ','USA','state','10','current','occupied','','34','N.J.','II','1','Northeast','2','Mid-Atlantic','3');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('31','New Mexico','NM','USA','state','10','current','occupied','','35','N.M.','VI','4','West','8','Mountain','10');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('32','New York','NY','USA','state','10','current','occupied','','36','N.Y.','II','1','Northeast','2','Mid-Atlantic','2');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('33','North Carolina','NC','USA','state','10','current','occupied','','37','N.C.','IV','3','South','5','South Atlantic','4');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('34','North Dakota','ND','USA','state','10','current','occupied','','38','N.D.','VIII','2','Midwest','4','West North Central','8');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('35','Ohio','OH','USA','state','10','current','occupied','','39','Ohio','V','2','Midwest','3','East North Central','6');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('36','Oklahoma','OK','USA','state','10','current','occupied','','40','Okla.','VI','3','South','7','West South Central','10');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('37','Oregon','OR','USA','state','10','current','occupied','','41','Ore.','X','4','West','9','Pacific','9');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('38','Pennsylvania','PA','USA','state','10','current','occupied','','42','Pa.','III','1','Northeast','2','Mid-Atlantic','3');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('39','Rhode Island','RI','USA','state','10','current','occupied','','44','R.I.','I','1','Northeast','1','New England','1');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('40','South Carolina','SC','USA','state','10','current','occupied','','45','S.C.','IV','3','South','5','South Atlantic','4');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('41','South Dakota','SD','USA','state','10','current','occupied','','46','S.D.','VIII','2','Midwest','4','West North Central','8');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('42','Tennessee','TN','USA','state','10','current','occupied','','47','Tenn.','IV','3','South','6','East South Central','6');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('43','Texas','TX','USA','state','10','current','occupied','','48','Texas','VI','3','South','7','West South Central','5');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('44','Utah','UT','USA','state','10','current','occupied','','49','Utah','VIII','4','West','8','Mountain','10');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('45','Vermont','VT','USA','state','10','current','occupied','','50','Vt.','I','1','Northeast','1','New England','2');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('46','Virginia','VA','USA','state','10','current','occupied','','51','Va.','III','3','South','5','South Atlantic','4');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('47','Washington','WA','USA','state','10','current','occupied','','53','Wash.','X','4','West','9','Pacific','9');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('48','West Virginia','WV','USA','state','10','current','occupied','','54','W.Va.','III','3','South','5','South Atlantic','4');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('49','Wisconsin','WI','USA','state','10','current','occupied','','55','Wis.','V','2','Midwest','3','East North Central','7');
INSERT INTO state (id,name,abbreviation,country,type,sort,status,occupied,notes,fips_state,assoc_press,standard_federal_region,census_region,census_region_name,census_division,census_division_name,circuit_court) VALUES ('50','Wyoming','WY','USA','state','10','current','occupied','','56','Wyo.','VIII','4','West','8','Mountain','10');
